---
version: '3.4'
services:
  proxy:
    image: marvinroesch/harmony-proxy:latest
    build:
      context: .
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend

  frontend:
    image: marvinroesch/harmony-frontend:latest
    build:
      context: frontend
      target: ${ENV:-dev}
    volumes:
      - ./frontend:/app
      - frontend_modules:/app/node_modules
    depends_on:
      - backend
    stdin_open: true
    tty: true

  backend:
    image: marvinroesch/harmony-backend:latest
    build:
      context: backend
      target: ${ENV:-dev}
    env_file:
      - ./backend/.env
    environment:
      - DB_URL=postgres://harmony:h4rm0ny@db/harmony
    volumes:
      - ./backend:/app
      - backend_modules:/app/node_modules
    depends_on:
      - db
    stdin_open: true
    tty: true

  bot:
    image: marvinroesch/harmony-bot:latest
    container_name: harmony-bot
    build:
      context: .
      dockerfile: Dockerfile-gradle
      target: bot
    env_file:
      - ./bot/.env
    environment:
      - DB_CONNECTION=jdbc:postgresql://db/harmony
      - DB_DRIVER=org.postgresql.Driver
      - DB_USER=harmony_imports
      - DB_PASSWORD=imp0rt5
      - ELASTIC_HOST=http://elasticsearch:9200

  db:
    image: postgres:12
    container_name: harmony-db
    environment:
      - POSTGRES_PASSWORD=example
      - DB_IMPORT_USER=harmony_imports
      - DB_IMPORT_PASSWORD=imp0rt5
      - DB_DATA_USER=harmony
      - DB_DATA_PASSWORD=h4rm0ny
    ports:
      - "5432:5432"
    volumes:
      - ./database-init:/docker-entrypoint-initdb.d

  elasticsearch:
    image: marvinroesch/harmony-elasticsearch:latest
    container_name: harmony-search
    build:
      context: ./elastic
      dockerfile: Dockerfile-elasticsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - "9300:9300"
      - "9200:9200"

volumes:
  frontend_modules:
  backend_modules:
  esdata:
